

INSERT INTO `videos` (`id`, `subtitle`, `title`, `avatar`, `content`, `button`, `urlZoom`, `urlYoutube`, `date`, `created_at`, `updated_at`, `hojaVida`) VALUES
(1, '14:20 INAUGURACIÓN:', 'Dr. Juan Carlos Torrez', 'https://lh3.googleusercontent.com/u/0/d/1kndpmBJlKjKQuVT0FENNWROonx0TjpBZ=w2000-h2820-iv1', '<b>Presidente  de  La  Sociedad  Boliviana  de  Neurología filial La Paz</b>', 1, '', NULL, '2023-09-13', NULL, NULL, '0'),
(2, '14:45 MONITOREO NO INVASIVO DE PACIENTE NEUROCRITICO', 'Dr. Roberto Zelaya Flores (ORURO)', 'https://lh3.googleusercontent.com/drive-viewer/AITFw-wwfmpFvvZ3A2h9nJ8v11tHqalkoqlVus0bQ_nJAQpIIU3KIWaYLR3L5VbPpuTJzjYCbSBRgHH08GcMDoOJKMiqZEdgrA=w811-h657', '', 1, 'http://www.google.com.bo', 'http://www.google.com.bo', '2023-09-13', NULL, NULL, '0'),
(3, '15:15 DEPRESION POST COVID', ' Dra. Magaly Gonzales Lemus  (ORURO)', 'https://lh3.googleusercontent.com/u/0/d/1l9t6I_MX1PYZB7v1PbWwl19CobVascxp=w2000-h2820-iv1', NULL, 1, 'http://www.google.com.bo', ' http://www.google.com.bo', '2023-09-13', NULL, NULL, 'https://drive.google.com/drive/my-drive'),
(4, '15:45 CARDIOEMBOLISMO EN STROKE ', 'Dra. Paola  Mancilla Oros (ORURO)', 'https://lh3.googleusercontent.com/u/0/d/1anVizj6pUKTdpgUkJ7f5f9MpCPohOByd=w800-h1128-iv1', NULL, 1, 'http://www.google.com.bo', ' http://www.google.com.bo', '2023-09-13', NULL, NULL, 'https://drive.google.com/drive/my-drive'),
(5, '14:30   PRIMO CRISIS EPILEPTICA ', 'Dra. Natali Sanchez Ortiz (SANTA CRUZ)', 'https://lh3.googleusercontent.com/u/0/d/1FFipUA9k0R6GO5XF9W8oxUcsNcrE9y9-=w388-h290-p-k-nu-iv1', NULL, 1, 'http://www.google.com.bo', ' http://www.google.com.bo', '2023-09-14', NULL, NULL, 'https://drive.google.com/drive/my-drive'),
(6, '15:30 PRIMO GIOVI', 'Dra. Natali Sanchez Ortiz (SANTA CRUZ)', 'https://lh3.googleusercontent.com/u/0/d/1FFipUA9k0R6GO5XF9W8oxUcsNcrE9y9-=w388-h290-p-k-nu-iv1', '', 1, 'http://www.google.com.bo', ' http://www.google.com.bo', '2023-09-14', NULL, NULL, 'https://drive.google.com/drive/my-drive');
